steps:
  - id: "get build number"
    name: gcr.io/cloud-builders/git
    dir: 'cloudbuild-dataflow-demo/streaming'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git rev-parse --short HEAD > _BUILDNUMBER
    waitFor: ['-']

  - id: "build and submit the dataflow job"
    name: maven:3.6.0-jdk-11-slim
    dir: 'cloudbuild-dataflow-demo/streaming'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        buildNumber=$(cat _BUILDNUMBER)
        bash ~/submit.sh DataflowDemoPipeline \
          --project=kissam-testing-project \
          --stagingLocation=gs://test-bucket-dg/ \
          --gcpTempLocation=gs://test-bucket-dg/ \
          --runner=DataflowRunner \
          --autoscalingAlgorithm=THROUGHPUT_BASED \
          --maxNumWorkers=10 \
          --jobName=demo \
          --buildNumber=${buildNumber} \
          --subscription=sub1 \
          --region=us-west1
    waitFor: ['get build number']
