steps:
  - id: "get build number"
    name: gcr.io/cloud-builders/git
    dir: 'cloudbuild-dataflow-demo/streaming'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git rev-parse --short HEAD > _BUILDNUMBER
    waitFor: ['-']

  - id: "upgrade wheel"
    name: python
    dir: 'cloudbuild-dataflow-demo/streaming'
    entrypoint: python
    args: ["-m", "pip", "install", "--upgrade", "wheel"]
    
  - id: "upgrade beam"
    name: python
    dir: 'cloudbuild-dataflow-demo/streaming'
    entrypoint: python
    args: ["-m", "pip", "install", "--upgrade", "apache-beam[gcp]"]
    waitFor: ['upgrade wheel']
   
  - id: "build and submit the dataflow job"
    name: python
    dir: '/workspace/streaming'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pwd
        ls
        bash submit2.sh main.py \
          --project=kissam-testing-project \
          --staging_location=gs://test-bucket-dg/stage/ \
          --temp_location=gs://test-bucket-dg/temp/ \
          --runner=DataflowRunner \
          --autoscaling_algorithm=THROUGHPUT_BASED \
          --max_num_workers=10 \
          --job_name=demo \
          --topic=projects/kissam-testing-project/topics/topico \
          --region=us-west1
    waitFor: ['get build number', 'upgrade beam']
